version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turbo-frontend
    expose:
      - "3000"  # Доступно только внутри Docker-сети
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    networks:
      - web
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: turbo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - frontend
    networks:
      - web
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: turbo-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge