name: CI/CD for React Shop Frontend

on:
  push:
    branches: [ frontend_shop ]
  pull_request:
    branches: [ frontend_shop ]

jobs:
  init:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Say Hello
      run: echo "Start deploy"
      
    - name: Show date
      run: date

  deploy-to-prod:
    needs: init
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Entering to project directory"
          cd /home/turbo-shop_frontend
          
          echo "Stopping running container"
          CONTAINER_ID=$(docker ps -q)
          if [ ! -z "$CONTAINER_ID" ]; then
            docker kill $CONTAINER_ID
          fi
          
          echo "Building new Docker image"
          docker buildx build --platform linux/amd64 -t my-react-app --load .
          
          echo "Starting new container"
          docker run -p 3000:3000 -d my-react-app
          
          echo "Cleaning up old images"
          docker image prune -f
          
    - name: Verify deployment
      run: |
        echo "Deployment completed at $(date)"
        echo "Application should be available at http://${{ secrets.SSH_HOST }}:3000"
