name: Deploy to Server

on:
  push:
    branches: [ "frontend_shop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Test SSH connection
      run: |
        ssh -v -o StrictHostKeyChecking=no \
        ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
        "echo 'Success!'; whoami; pwd"
    
    - name: Connect
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

    - name: Where I am
      run: "pwd"

    - name: Entering to dir
      run: "cd /home/turbo-shop_frontend"

    - name: Pulling updates
      run: "git pull"

    - name: Stopping containers
      run: "docker stop $(docker ps -q)"

    - name: Building new image
      run: "docker buildx build --platform linux/amd64 -t my-react-app --load ."

    - name: Starting container
      run: "docker run -p 3000:3000 -d my-react-app"

    - name: Cleaning up
      run: "docker image prune -f"
