name: Deploy to Server

on:
  push:
    branches: [ "frontend_shop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Test SSH connection
      run: |
        ssh -v -o StrictHostKeyChecking=no \
        ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
        "echo 'Success!'; whoami; pwd"
    
    - name: Connect, deploy, build and start
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/turbo-shop_frontend
          git fetch origin frontend_shop
          git reset --hard origin/frontend_shop
          docker compose stop
          docker compose up --build -d
        EOF
