name: CI/CD for React Shop Frontend

on:
  push:
    branches: [ frontend_shop ]
  pull_request:
    branches: [ frontend_shop ]

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install SSHpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        
    - name: Execute deployment via SSH (password)
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} << 'EOF'
          echo "Entering project directory..."
          cd /home/turbo-shop_frontend || exit 1
          
          echo "Stopping containers..."
          docker stop $(docker ps -q) || echo "No containers running"
          
          echo "Building new image..."
          docker buildx build --platform linux/amd64 -t my-react-app --load . || exit 1
          
          echo "Starting container..."
          docker run -p 3000:3000 -d my-react-app || exit 1
          
          echo "Cleaning up..."
          docker image prune -f
          echo "Deployment successful!"
        EOF
          
    - name: Verify deployment
      run: |
        echo "Deployment completed at $(date)"
        echo "App available at: http://${{ secrets.SSH_HOST }}:3000"
