name: Deploy to Server

on:
  push:
    branches: [ "frontend_shop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Connect and deploy
      run: |
        ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "echo 'Entering project directory...' && \
             cd /home/turbo-shop_frontend || exit 1 && \
             
             echo 'Pulling latest changes...' && \
             git pull origin frontend_shop || exit 1 && \
             
             echo 'Stopping containers...' && \
             docker stop $(docker ps -q) || echo 'No containers running' && \
             
             echo 'Building new image...' && \
             docker buildx build --platform linux/amd64 -t my-react-app --load . || exit 1 && \
             
             echo 'Starting container...' && \
             docker run -p 3000:3000 -d my-react-app || exit 1 && \
             
             echo 'Cleaning up...' && \
             docker image prune -f && \
             
             echo 'Deployment successful!'"
