name: Deploy to Server

on:
  push:
    branches: [ "frontend_shop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Test SSH connection
      run: |
        ssh -v -o StrictHostKeyChecking=no \
        ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
        "echo 'Success!'; whoami; pwd"
    
    - name: Connect, deploy, build and start
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/runner/work/turbo_auto_saloon/turbo_auto_saloon
          git fetch origin frontend_shop
          git reset --hard origin/frontend_shop
          docker ps -q | xargs -r docker kill
          docker buildx build --platform linux/amd64 -t my-react-app --load .
          docker run -p 3000:3000 -d my-react-app
        EOF